name: Destroy Dev Infrastructure
on:
    workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
  pull-requests: write
 
env:
  TF_VAR_AWS_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
  TF_VAR_AWS_SECRET_KEY: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}
  TF_VAR_AWS_REGION: ${{ secrets.TF_VAR_AWS_REGION }}

  TF_VAR_API_SERVICE: ${{ secrets.TF_VAR_API_SERVICE }}
  TF_VAR_API_EMAIL: ${{ secrets.TF_VAR_API_EMAIL }}
  TF_VAR_API_PASSWORD: ${{ secrets.TF_VAR_API_PASSWORD }}
  TF_VAR_API_IMAGE: ${{ secrets.TF_VAR_API_EMAIL }}
  TF_VAR_API_JWT_SECRET: ${{ secrets.TF_VAR_API_JWT_SECRET }}
  TF_VAR_API_JWT_EXPIRATION: ${{ secrets.TF_VAR_API_JWT_EXPIRATION }}
  TF_VAR_API_PORT: ${{ secrets.TF_VAR_API_PORT }}
  TF_VAR_DB_USER: ${{ secrets.TF_VAR_DB_USER }}
  TF_VAR_DB_NAME: ${{ secrets.TF_VAR_DB_NAME }}
  TF_VAR_DB_PASS: ${{ secrets.TF_VAR_DB_PASS }}
  TF_VAR_DB_PORT: ${{ secrets.TF_VAR_DB_PORT }}
  TF_VAR_API_URL: ${{ secrets.TF_VAR_API_URL }}
  TF_VAR_APP_IMAGE: ${{ secrets.TF_VAR_APP_IMAGE }}

  TF_VAR_AWS_ENV: ${{ secrets.TF_VAR_AWS_ENV }}
  TF_VAR_AWS_SERVER_NAME: ${{ secrets.TF_VAR_AWS_SERVER_NAME }}
  TF_VAR_AWS_KEY_PAIR_NAME: ${{ secrets.TF_VAR_AWS_KEY_PAIR_NAME }}
  TF_VAR_AWS_SG_NAME: ${{ secrets.TF_VAR_AWS_SG_NAME }}
  
  TF_VAR_MAIN_DOMAIN: ${{ secrets.TF_VAR_MAIN_DOMAIN }}
 
jobs:
    terraform-plan-apply:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
 
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE }}
                aws-region: ${{ secrets.TF_VAR_AWS_REGION }}
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Create SSH Keys from secrets
              run: |
                mkdir -p ./envs/dev/keys
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./envs/dev/keys/aws_node_app_key
                echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./envs/dev/keys/aws_node_app_key.pub
                chmod 600 ./envs/dev/keys/aws_node_app_key
                chmod 644 ./envs/dev/keys/aws_node_app_key.pub
              
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.9.2
                terraform_wrapper: false
            
            - name: Terraform init
              run: terraform -chdir=envs/dev init
 
            - name: Terraform format
              run: terraform -chdir=envs/dev fmt
 
            - name: Terraform plan
              run: terraform -chdir=envs/dev plan
 
            - name: Terraform destroy
              run: terraform -chdir=envs/dev destroy --auto-approve